### PR TITLE
fixed typos in README.md

### PR DESCRIPTION
**Pull request by AdamJel**
Few typos fixed.

### CODE REVIEW

**Comment by namjaejeon** [comment]
Hi,

Your patch looks good to me.
And there are no Signed-off-by in patch and prefix "exfat-utils:" in subject.
You can reference another patch in my pull request of https://github.com/exfat-utils/exfat-utils.
I think that you didn't create patches using git. Can you recreate the patch using git ?

One more thing, Coud you send pull request to #exfat-next branch of https://github.com/exfat-utils/exfat-utils instead of my git tree ? Normally we push patches to next branch first, and move them to master after testing.

Thanks!

**Comment by namjaejeon** [comment]
@AdamJel hm.. no response. Coud you please tell me your mail address to use it in your patch ? I will directly create the patch using git instead of you.

**Comment by AdamJel** [comment]
> 
> 
> @AdamJel hm.. no response. Coud you please tell me your mail address to use it in your patch ? I will directly create the patch using git instead of you.

Hello, sorry for late reply. I didnt check gh during Easter. 

I am on it.

**Comment by namjaejeon** [comment]
@AdamJel Okay. Could you please read above my request ?

**Comment by AdamJel** [comment]
@namjaejeon Yes, I did. I am trying to sign-off the commit. I have troubles with that though. Maybe you can help me out? 

I successfully added my gpg key and changed my --author per commit, so the author and signature is correct for the commit, but the author in Signed-off-by line is still wrong and I cant find a way to fix it.

obrazek

**Comment by namjaejeon** [comment]
Ah, I don't understand why you added your gpg key. You don't need to do it.
Have you set up your .gitconfig ? This is my gitconfig.
[user]
      name = Namjae Jeon
      email = linkinjeon@kernel.org
signoff-by is created using user info in .gitconfig.

So you can do the following ones.
 1. git clone --branch=exfat-next https://github.com/exfat-utils/exfat-utils
 2. change README file.
 3. check if your change is correct or not using "git diff"
 4. git commit -asm "exfat-utils: update README file
           Fixes few typos. Replaced tabs with spaces"
 5. git format-patch -1 => check your signoff and contents in patch file.
 6. git push origin exfat-next
 7. send a pull request to #exfat-next branch in exfat-utils.

Let me know if you have problem.
Thanks.

**Comment by AdamJel** [comment]
Ok, all done. Hopefully, it'll be fine now. Thank you for your guidance.

**Pull request closed without merging**
