### PR TITLE
bump version to replace exfat

### LINKED ISSUE #40: How does this is related to https://github.com/relan/exfat
Hi,

https://github.com/relan/exfat released v1.3.0 in 2018. How that release is related to yours 1.0.1 ?
If yours 1.0.1 is successor than please bump the version to be higher tnat 1.3.0 so distributions and packages may handle this upgrade easier.

### PR DESCRIPTION
**Pull request by tpgxyz**
exfat-utils version should be higher than https://github.com/relan/exfat
fix #40

This will help to all packagers and maintainers in downstream distributions to help update over exfat-1.3.0

### CODE REVIEW

**Comment by namjaejeon** [comment]
@tpgxyz I decide to rename exfat-utils to exfatprogs. please read this address.
https://lkml.org/lkml/2020/4/15/1885

Thanks!

**Comment by tpgxyz** [comment]
@namjaejeon anyways exfatprogs version should be still bigger than exfat as both software provides same binaries

**Comment by namjaejeon** [comment]
@tpgxyz mkfs/fsck -V will display exfatprogs version(not exfat-utils) like this.
#>mkfs.exfat -V
exfatprogs version : 1.0.2

**Comment by tpgxyz** [comment]
@namjaejeon pleae notice that distributions which provides exfat-utils = 1.3.0 also provide
/usr/bin/mkfs.exfat
in case of RPM (guess same situation on DEB) packaging you will have a conflicting files.

So as i wrote a maintainers and packagers will must add some weird workarounds to replace exfat-utils = 1.3.0 with exfatprogs = 1.0.2 as both provides almost the same binaries like mkfs.exfat
Notice:
1.3.0 > 1.0.2

Easiest solution that does not cost anything is to bump version of exfatprogs to be higher that exfat-utils i.e 1.3.1
 Thanks.

**Comment by namjaejeon** [comment]
@tpgxyz We have the time till linux-5.7 kernel release out. This utilies is for exfat filesystem in linux kernel. I don't like to increment version number without updating code, Especially long jump. As I said on ISSUE you raise, I will consider version upgrade to >1.3.1 of exfatprogs with new feature(repair).

**Comment by namjaejeon** [comment]
merge conflict and I have explained enough.

**Pull request closed without merging**
